### ISSUE TITLE
Can you please tell me how long it will take to process 1000 images on a nvidia v100 video card?

### ISSUE THREAD

**Issue by sharingan000** [DS4SD/MolGrapher#4]
Can you please tell me how long it will take to process 1000 images on a nvidia v100 video card? 

P.S. I need gpu docker file, if you don't mind

**Comment by lucas-morin** [comment]
Hello, 

Unfortunately, I haven't measured performances with an NVIDIA V100 GPU. 
To give you an order of magnitude, on a machine equipped with one NVIDIA A100 GPU and AMD EPYC 7763 CPU, processing images by batches of 20, MolGrapher annotates an average of 3.1 images per second.

Best,
Lucas
