### ISSUE TITLE
Superatom Groups Recognition Error

### ISSUE THREAD

**Issue by sincelover** [DS4SD/MolGrapher#7]
Hi, dear developers!
Thank you very much for code sharing!

When I use gc_gcn_model to make predictions, almost all of the results appear to have Superatom Groups Recognition Error.An example is shown below.
But no such problem occurs when I use the other two models.
I wonder if there's a problem with the ocr settings.

image:
![1](https://github.com/DS4SD/MolGrapher/assets/96339887/63cf39ea-c042-414a-828a-3e980c74af51)
result:
![屏幕截图 2024-05-27 184614](https://github.com/DS4SD/MolGrapher/assets/96339887/034b9720-90f3-4755-8f09-7f62d96bfddf)

**Comment by lucas-morin** [comment]
The `gc_gcn_model` available does not support the recognition of superatoms (as well as atom charges). 
For such molecules, please use `gc_no_stereo_model` or `gc_stereo_model`.

Best, 
Lucas

**Comment by sincelover** [comment]
thank you so much

**Comment by sincelover** [comment]
I get it.Thank you very much!
