### ISSUE TITLE
I want to know how you set the kinds of atoms

### ISSUE THREAD

**Issue by pjc12345678** [DS4SD/MolGrapher#9]
brilliant your work. But I noticed that there are three vocabularies of atoms in your codes, which is 120,141,182. so what do you base your vocabularies on that generate differ numbers. 
hope for you reply.

**Comment by lucas-morin** [comment]
Hello, thanks you! 

The vocabulary with `141` atom classes do not cover atoms with charges. It can be used to run `gc_gcn_model`.
The vocabulary with `182` atom classes can be used to run other models. 
If I remember correctly, the vocabulary with `120` atom classes can be ignored, as it was used for early versions of the models. I remove it. 

Best, 
Lucas

**Comment by pjc12345678** [comment]
thank you for you reply.  I am interested in how to generate image with label about types of atoms or bonds. but I can only find code of generating image with label about the coordinate of atoms and bonds in MolDepictor. so can you give me some tips to find the code. 

hope for you reply
